"""Database models for CDP Lite."""

from datetime import datetime, timezone
from typing import Any

from sqlalchemy import JSON, DateTime, ForeignKey, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db import Base


class CustomerProfile(Base):
    """A unified customer identity and its core attributes."""

    __tablename__ = "customer_profiles"

    id: Mapped[int] = mapped_column(primary_key=True)
    external_id: Mapped[str] = mapped_column(String(100), unique=True, index=True)
    email: Mapped[str | None] = mapped_column(String(255), unique=True, index=True)
    first_name: Mapped[str | None] = mapped_column(String(100))
    last_name: Mapped[str | None] = mapped_column(String(100))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )
    events: Mapped[list["CustomerEvent"]] = relationship(
        back_populates="profile",
        cascade="all, delete-orphan",
    )


class CustomerEvent(Base):
    """An action generated by a customer profile."""

    __tablename__ = "customer_events"

    id: Mapped[int] = mapped_column(primary_key=True)
    profile_id: Mapped[int] = mapped_column(
        ForeignKey("customer_profiles.id"),
        index=True,
    )
    event_type: Mapped[str] = mapped_column(String(100), index=True)
    event_data: Mapped[dict[str, Any]] = mapped_column(JSON, default=dict)
    occurred_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )
    profile: Mapped[CustomerProfile] = relationship(back_populates="events")
